# Generated by Django 5.0 on 2024-01-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_task_complete_user_task_task_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_complete_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
