# Generated by Django 5.0 on 2024-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_task_complete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_project_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
