# Generated by Django 5.0 on 2024-01-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_task_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
